name: Coding Standard

on:
  pull_request:
    branches:
      - develop
      - master
      - 'release/**'
      - 'rc/**'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # or any version you are using
          tools: composer

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache PHP Dependencies
        id: composer-cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-7.2-${{ hashFiles('composer.lock') }}

      - name: Install PHP Dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: PHPCS cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: tests/cache
          key: ${{ runner.os }}-phpcs-7.2-${{ hashFiles('plugin.php') }}

      - name: Determine changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          list-files: shell
          filters: |
            php:
              - 'includes/**/*.php'
              - 'includes/**'

      - name: Run PHPCS
        if: steps.filter.outputs.php_files != ''
        run: |
          ./vendor/bin/phpcs --standard=phpcs.xml ${GITHUB_WORKSPACE}/${{ steps.filter.outputs.php_files }}
